// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Predicate",
			pos:  position{line: 6, col: 1, offset: 55},
			expr: &choiceExpr{
				pos: position{line: 6, col: 13, offset: 69},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 6, col: 13, offset: 69},
						name: "PredNumericEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 32, offset: 88},
						name: "PredNumericNotEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 54, offset: 110},
						name: "PredBoolNotEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 73, offset: 129},
						name: "PredBoolEqual",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 89, offset: 145},
						name: "PredNumericWrongTypes",
					},
					&ruleRefExpr{
						pos:  position{line: 6, col: 113, offset: 169},
						name: "PredBoolWrongTypes",
					},
				},
			},
		},
		{
			name: "PredNumericEqual",
			pos:  position{line: 7, col: 1, offset: 189},
			expr: &actionExpr{
				pos: position{line: 7, col: 20, offset: 210},
				run: (*parser).callonPredNumericEqual1,
				expr: &seqExpr{
					pos: position{line: 7, col: 20, offset: 210},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 7, col: 20, offset: 210},
							label: "left",
							expr: &choiceExpr{
								pos: position{line: 7, col: 26, offset: 216},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 7, col: 26, offset: 216},
										name: "NumberVal",
									},
									&ruleRefExpr{
										pos:  position{line: 7, col: 38, offset: 228},
										name: "TemplateVal",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 51, offset: 241},
							name: "OpNumericEqual",
						},
						&labeledExpr{
							pos:   position{line: 7, col: 66, offset: 256},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 7, col: 73, offset: 263},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 7, col: 73, offset: 263},
										name: "NumberVal",
									},
									&ruleRefExpr{
										pos:  position{line: 7, col: 85, offset: 275},
										name: "TemplateVal",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PredNumericNotEqual",
			pos:  position{line: 10, col: 1, offset: 399},
			expr: &actionExpr{
				pos: position{line: 10, col: 23, offset: 423},
				run: (*parser).callonPredNumericNotEqual1,
				expr: &seqExpr{
					pos: position{line: 10, col: 23, offset: 423},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 10, col: 23, offset: 423},
							label: "left",
							expr: &choiceExpr{
								pos: position{line: 10, col: 29, offset: 429},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 10, col: 29, offset: 429},
										name: "NumberVal",
									},
									&ruleRefExpr{
										pos:  position{line: 10, col: 41, offset: 441},
										name: "TemplateVal",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 54, offset: 454},
							name: "OpNumericNotEqual",
						},
						&labeledExpr{
							pos:   position{line: 10, col: 72, offset: 472},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 10, col: 79, offset: 479},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 10, col: 79, offset: 479},
										name: "NumberVal",
									},
									&ruleRefExpr{
										pos:  position{line: 10, col: 91, offset: 491},
										name: "TemplateVal",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PredBoolNotEqual",
			pos:  position{line: 13, col: 1, offset: 629},
			expr: &choiceExpr{
				pos: position{line: 13, col: 20, offset: 650},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 13, col: 20, offset: 650},
						run: (*parser).callonPredBoolNotEqual2,
						expr: &seqExpr{
							pos: position{line: 13, col: 20, offset: 650},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 13, col: 20, offset: 650},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 13, col: 25, offset: 655},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 13, col: 37, offset: 667},
									expr: &ruleRefExpr{
										pos:  position{line: 13, col: 37, offset: 667},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 13, col: 49, offset: 679},
									name: "OpBoolNotEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 13, col: 64, offset: 694},
									expr: &ruleRefExpr{
										pos:  position{line: 13, col: 64, offset: 694},
										name: "Whitespace",
									},
								},
								&choiceExpr{
									pos: position{line: 13, col: 77, offset: 707},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 13, col: 77, offset: 707},
											name: "LVNull",
										},
										&ruleRefExpr{
											pos:  position{line: 13, col: 86, offset: 716},
											name: "LVNil",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 15, col: 5, offset: 819},
						run: (*parser).callonPredBoolNotEqual14,
						expr: &seqExpr{
							pos: position{line: 15, col: 5, offset: 819},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 15, col: 5, offset: 819},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 10, offset: 824},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 15, col: 22, offset: 836},
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 22, offset: 836},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 15, col: 34, offset: 848},
									name: "OpBoolNotEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 15, col: 49, offset: 863},
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 49, offset: 863},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 15, col: 61, offset: 875},
									name: "LVTrue",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 17, col: 5, offset: 979},
						run: (*parser).callonPredBoolNotEqual24,
						expr: &seqExpr{
							pos: position{line: 17, col: 5, offset: 979},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 17, col: 5, offset: 979},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 10, offset: 984},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 17, col: 22, offset: 996},
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 22, offset: 996},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 17, col: 34, offset: 1008},
									name: "OpBoolNotEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 17, col: 49, offset: 1023},
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 49, offset: 1023},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 17, col: 61, offset: 1035},
									name: "LVFalse",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PredBoolEqual",
			pos:  position{line: 20, col: 1, offset: 1140},
			expr: &choiceExpr{
				pos: position{line: 20, col: 17, offset: 1158},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 20, col: 17, offset: 1158},
						run: (*parser).callonPredBoolEqual2,
						expr: &seqExpr{
							pos: position{line: 20, col: 17, offset: 1158},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 20, col: 17, offset: 1158},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 22, offset: 1163},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 20, col: 34, offset: 1175},
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 34, offset: 1175},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 46, offset: 1187},
									name: "OpBoolEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 20, col: 58, offset: 1199},
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 58, offset: 1199},
										name: "Whitespace",
									},
								},
								&choiceExpr{
									pos: position{line: 20, col: 71, offset: 1212},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 20, col: 71, offset: 1212},
											name: "LVNull",
										},
										&ruleRefExpr{
											pos:  position{line: 20, col: 80, offset: 1221},
											name: "LVNil",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 22, col: 5, offset: 1310},
						run: (*parser).callonPredBoolEqual14,
						expr: &seqExpr{
							pos: position{line: 22, col: 5, offset: 1310},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 22, col: 5, offset: 1310},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 10, offset: 1315},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 22, col: 22, offset: 1327},
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 22, offset: 1327},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 34, offset: 1339},
									name: "OpBoolEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 22, col: 46, offset: 1351},
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 46, offset: 1351},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 22, col: 58, offset: 1363},
									name: "LVTrue",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 24, col: 5, offset: 1453},
						run: (*parser).callonPredBoolEqual24,
						expr: &seqExpr{
							pos: position{line: 24, col: 5, offset: 1453},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 24, col: 5, offset: 1453},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 10, offset: 1458},
										name: "TemplateVal",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 24, col: 22, offset: 1470},
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 22, offset: 1470},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 24, col: 34, offset: 1482},
									name: "OpBoolEqual",
								},
								&oneOrMoreExpr{
									pos: position{line: 24, col: 46, offset: 1494},
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 46, offset: 1494},
										name: "Whitespace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 24, col: 58, offset: 1506},
									name: "LVFalse",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PredNumericWrongTypes",
			pos:  position{line: 30, col: 1, offset: 1674},
			expr: &actionExpr{
				pos: position{line: 30, col: 25, offset: 1700},
				run: (*parser).callonPredNumericWrongTypes1,
				expr: &seqExpr{
					pos: position{line: 30, col: 25, offset: 1700},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 30, col: 25, offset: 1700},
							name: "Value",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 31, offset: 1706},
							label: "cmbn",
							expr: &choiceExpr{
								pos: position{line: 30, col: 37, offset: 1712},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 30, col: 37, offset: 1712},
										name: "OpNumericNotEqual",
									},
									&ruleRefExpr{
										pos:  position{line: 30, col: 57, offset: 1732},
										name: "OpNumericEqual",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 73, offset: 1748},
							name: "Value",
						},
					},
				},
			},
		},
		{
			name: "PredBoolWrongTypes",
			pos:  position{line: 34, col: 1, offset: 2055},
			expr: &actionExpr{
				pos: position{line: 34, col: 22, offset: 2078},
				run: (*parser).callonPredBoolWrongTypes1,
				expr: &seqExpr{
					pos: position{line: 34, col: 22, offset: 2078},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 34, col: 22, offset: 2078},
							name: "Value",
						},
						&labeledExpr{
							pos:   position{line: 34, col: 28, offset: 2084},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 34, col: 32, offset: 2088},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 34, col: 32, offset: 2088},
										name: "OpBoolEqual",
									},
									&ruleRefExpr{
										pos:  position{line: 34, col: 46, offset: 2102},
										name: "OpBoolNotEqual",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 62, offset: 2118},
							name: "Value",
						},
					},
				},
			},
		},
		{
			name: "OpNumericEqual",
			pos:  position{line: 39, col: 1, offset: 2404},
			expr: &choiceExpr{
				pos: position{line: 39, col: 19, offset: 2424},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 39, col: 20, offset: 2425},
						exprs: []interface{}{
							&oneOrMoreExpr{
								pos: position{line: 39, col: 20, offset: 2425},
								expr: &ruleRefExpr{
									pos:  position{line: 39, col: 20, offset: 2425},
									name: "Ws",
								},
							},
							&choiceExpr{
								pos: position{line: 39, col: 25, offset: 2430},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 39, col: 25, offset: 2430},
										val:        "equals",
										ignoreCase: true,
									},
									&litMatcher{
										pos:        position{line: 39, col: 37, offset: 2442},
										val:        "equal",
										ignoreCase: true,
									},
								},
							},
							&oneOrMoreExpr{
								pos: position{line: 39, col: 47, offset: 2452},
								expr: &ruleRefExpr{
									pos:  position{line: 39, col: 47, offset: 2452},
									name: "Ws",
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 39, col: 54, offset: 2459},
						exprs: []interface{}{
							&zeroOrMoreExpr{
								pos: position{line: 39, col: 54, offset: 2459},
								expr: &ruleRefExpr{
									pos:  position{line: 39, col: 54, offset: 2459},
									name: "Ws",
								},
							},
							&litMatcher{
								pos:        position{line: 39, col: 58, offset: 2463},
								val:        "==",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 39, col: 63, offset: 2468},
								expr: &ruleRefExpr{
									pos:  position{line: 39, col: 63, offset: 2468},
									name: "Ws",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OpNumericNotEqual",
			pos:  position{line: 40, col: 1, offset: 2473},
			expr: &choiceExpr{
				pos: position{line: 40, col: 21, offset: 2495},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 40, col: 22, offset: 2496},
						exprs: []interface{}{
							&oneOrMoreExpr{
								pos: position{line: 40, col: 22, offset: 2496},
								expr: &ruleRefExpr{
									pos:  position{line: 40, col: 22, offset: 2496},
									name: "Ws",
								},
							},
							&choiceExpr{
								pos: position{line: 40, col: 27, offset: 2501},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 40, col: 27, offset: 2501},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 40, col: 27, offset: 2501},
												val:        "not",
												ignoreCase: true,
											},
											&oneOrMoreExpr{
												pos: position{line: 40, col: 34, offset: 2508},
												expr: &ruleRefExpr{
													pos:  position{line: 40, col: 34, offset: 2508},
													name: "Ws",
												},
											},
											&litMatcher{
												pos:        position{line: 40, col: 38, offset: 2512},
												val:        "equals",
												ignoreCase: true,
											},
										},
									},
									&seqExpr{
										pos: position{line: 40, col: 50, offset: 2524},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 40, col: 50, offset: 2524},
												val:        "not",
												ignoreCase: true,
											},
											&oneOrMoreExpr{
												pos: position{line: 40, col: 57, offset: 2531},
												expr: &ruleRefExpr{
													pos:  position{line: 40, col: 57, offset: 2531},
													name: "Ws",
												},
											},
											&litMatcher{
												pos:        position{line: 40, col: 61, offset: 2535},
												val:        "equal",
												ignoreCase: true,
											},
										},
									},
								},
							},
							&oneOrMoreExpr{
								pos: position{line: 40, col: 71, offset: 2545},
								expr: &ruleRefExpr{
									pos:  position{line: 40, col: 71, offset: 2545},
									name: "Ws",
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 40, col: 78, offset: 2552},
						exprs: []interface{}{
							&zeroOrMoreExpr{
								pos: position{line: 40, col: 78, offset: 2552},
								expr: &ruleRefExpr{
									pos:  position{line: 40, col: 78, offset: 2552},
									name: "Ws",
								},
							},
							&litMatcher{
								pos:        position{line: 40, col: 82, offset: 2556},
								val:        "!=",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 40, col: 87, offset: 2561},
								expr: &ruleRefExpr{
									pos:  position{line: 40, col: 87, offset: 2561},
									name: "Ws",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OpStringEquals",
			pos:  position{line: 42, col: 1, offset: 2687},
			expr: &choiceExpr{
				pos: position{line: 42, col: 18, offset: 2706},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 42, col: 18, offset: 2706},
						val:        "equals",
						ignoreCase: true,
					},
					&litMatcher{
						pos:        position{line: 42, col: 30, offset: 2718},
						val:        "equal",
						ignoreCase: true,
					},
				},
			},
		},
		{
			name: "OpStringNotEqual",
			pos:  position{line: 43, col: 1, offset: 2728},
			expr: &choiceExpr{
				pos: position{line: 43, col: 20, offset: 2749},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 43, col: 20, offset: 2749},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 43, col: 20, offset: 2749},
								val:        "not",
								ignoreCase: true,
							},
							&oneOrMoreExpr{
								pos: position{line: 43, col: 27, offset: 2756},
								expr: &ruleRefExpr{
									pos:  position{line: 43, col: 27, offset: 2756},
									name: "Whitespace",
								},
							},
							&litMatcher{
								pos:        position{line: 43, col: 39, offset: 2768},
								val:        "equals",
								ignoreCase: true,
							},
						},
					},
					&seqExpr{
						pos: position{line: 43, col: 51, offset: 2780},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 43, col: 51, offset: 2780},
								val:        "not",
								ignoreCase: true,
							},
							&oneOrMoreExpr{
								pos: position{line: 43, col: 58, offset: 2787},
								expr: &ruleRefExpr{
									pos:  position{line: 43, col: 58, offset: 2787},
									name: "Whitespace",
								},
							},
							&litMatcher{
								pos:        position{line: 43, col: 70, offset: 2799},
								val:        "equal",
								ignoreCase: true,
							},
						},
					},
				},
			},
		},
		{
			name: "OpBoolEqual",
			pos:  position{line: 44, col: 1, offset: 2809},
			expr: &litMatcher{
				pos:        position{line: 44, col: 15, offset: 2825},
				val:        "is",
				ignoreCase: true,
			},
		},
		{
			name: "OpBoolNotEqual",
			pos:  position{line: 45, col: 1, offset: 2832},
			expr: &seqExpr{
				pos: position{line: 45, col: 18, offset: 2851},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 45, col: 18, offset: 2851},
						val:        "is",
						ignoreCase: true,
					},
					&oneOrMoreExpr{
						pos: position{line: 45, col: 24, offset: 2857},
						expr: &ruleRefExpr{
							pos:  position{line: 45, col: 24, offset: 2857},
							name: "Ws",
						},
					},
					&litMatcher{
						pos:        position{line: 45, col: 28, offset: 2861},
						val:        "not",
						ignoreCase: true,
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 48, col: 1, offset: 2974},
			expr: &choiceExpr{
				pos: position{line: 48, col: 9, offset: 2984},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 48, col: 9, offset: 2984},
						name: "StringVal",
					},
					&ruleRefExpr{
						pos:  position{line: 48, col: 21, offset: 2996},
						name: "TemplateVal",
					},
					&ruleRefExpr{
						pos:  position{line: 48, col: 35, offset: 3010},
						name: "NumberVal",
					},
					&ruleRefExpr{
						pos:  position{line: 48, col: 47, offset: 3022},
						name: "LiteralVal",
					},
				},
			},
		},
		{
			name: "LiteralVal",
			pos:  position{line: 51, col: 1, offset: 3111},
			expr: &choiceExpr{
				pos: position{line: 51, col: 14, offset: 3126},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 51, col: 14, offset: 3126},
						name: "LVTrue",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 23, offset: 3135},
						name: "LVFalse",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 33, offset: 3145},
						name: "LVNull",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 42, offset: 3154},
						name: "LVNil",
					},
				},
			},
		},
		{
			name: "LVTrue",
			pos:  position{line: 52, col: 1, offset: 3161},
			expr: &actionExpr{
				pos: position{line: 52, col: 10, offset: 3172},
				run: (*parser).callonLVTrue1,
				expr: &litMatcher{
					pos:        position{line: 52, col: 10, offset: 3172},
					val:        "true",
					ignoreCase: true,
				},
			},
		},
		{
			name: "LVFalse",
			pos:  position{line: 55, col: 1, offset: 3235},
			expr: &actionExpr{
				pos: position{line: 55, col: 11, offset: 3247},
				run: (*parser).callonLVFalse1,
				expr: &litMatcher{
					pos:        position{line: 55, col: 11, offset: 3247},
					val:        "false",
					ignoreCase: true,
				},
			},
		},
		{
			name: "LVNull",
			pos:  position{line: 58, col: 1, offset: 3312},
			expr: &actionExpr{
				pos: position{line: 58, col: 10, offset: 3323},
				run: (*parser).callonLVNull1,
				expr: &litMatcher{
					pos:        position{line: 58, col: 10, offset: 3323},
					val:        "null",
					ignoreCase: true,
				},
			},
		},
		{
			name: "LVNil",
			pos:  position{line: 61, col: 1, offset: 3375},
			expr: &actionExpr{
				pos: position{line: 61, col: 9, offset: 3385},
				run: (*parser).callonLVNil1,
				expr: &litMatcher{
					pos:        position{line: 61, col: 9, offset: 3385},
					val:        "nil",
					ignoreCase: true,
				},
			},
		},
		{
			name: "TemplateVal",
			pos:  position{line: 66, col: 1, offset: 3500},
			expr: &actionExpr{
				pos: position{line: 66, col: 15, offset: 3516},
				run: (*parser).callonTemplateVal1,
				expr: &labeledExpr{
					pos:   position{line: 66, col: 15, offset: 3516},
					label: "str",
					expr: &ruleRefExpr{
						pos:  position{line: 66, col: 19, offset: 3520},
						name: "UnquotedString",
					},
				},
			},
		},
		{
			name: "StringVal",
			pos:  position{line: 69, col: 1, offset: 3603},
			expr: &actionExpr{
				pos: position{line: 69, col: 13, offset: 3617},
				run: (*parser).callonStringVal1,
				expr: &labeledExpr{
					pos:   position{line: 69, col: 13, offset: 3617},
					label: "str",
					expr: &choiceExpr{
						pos: position{line: 69, col: 18, offset: 3622},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 69, col: 18, offset: 3622},
								name: "DoubleString",
							},
							&ruleRefExpr{
								pos:  position{line: 69, col: 33, offset: 3637},
								name: "SingleString",
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 79, col: 1, offset: 3953},
			expr: &choiceExpr{
				pos: position{line: 79, col: 10, offset: 3964},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 79, col: 10, offset: 3964},
						name: "DoubleString",
					},
					&ruleRefExpr{
						pos:  position{line: 79, col: 25, offset: 3979},
						name: "SingleString",
					},
					&ruleRefExpr{
						pos:  position{line: 79, col: 40, offset: 3994},
						name: "UnquotedString",
					},
				},
			},
		},
		{
			name: "SingleString",
			pos:  position{line: 81, col: 1, offset: 4066},
			expr: &actionExpr{
				pos: position{line: 81, col: 16, offset: 4083},
				run: (*parser).callonSingleString1,
				expr: &seqExpr{
					pos: position{line: 81, col: 16, offset: 4083},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 81, col: 16, offset: 4083},
							name: "SingleQuote",
						},
						&labeledExpr{
							pos:   position{line: 81, col: 28, offset: 4095},
							label: "chr",
							expr: &zeroOrMoreExpr{
								pos: position{line: 81, col: 32, offset: 4099},
								expr: &choiceExpr{
									pos: position{line: 81, col: 34, offset: 4101},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 81, col: 34, offset: 4101},
											exprs: []interface{}{
												&notExpr{
													pos: position{line: 81, col: 34, offset: 4101},
													expr: &ruleRefExpr{
														pos:  position{line: 81, col: 35, offset: 4102},
														name: "SingleEscapedChar",
													},
												},
												&anyMatcher{
													line: 81, col: 53, offset: 4120,
												},
											},
										},
										&seqExpr{
											pos: position{line: 81, col: 57, offset: 4124},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 81, col: 57, offset: 4124},
													val:        "\\",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 81, col: 62, offset: 4129},
													name: "SingleEscapeSequence",
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 81, col: 86, offset: 4153},
							name: "SingleQuote",
						},
					},
				},
			},
		},
		{
			name: "SingleEscapedChar",
			pos:  position{line: 84, col: 1, offset: 4210},
			expr: &charClassMatcher{
				pos:             position{line: 84, col: 21, offset: 4232},
				val:             "[\\x00-\\x1f'\\\\]",
				chars:           []rune{'\'', '\\'},
				ranges:          []rune{'\x00', '\x1f'},
				basicLatinChars: [128]bool{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "SingleEscapeSequence",
			pos:  position{line: 85, col: 1, offset: 4248},
			expr: &choiceExpr{
				pos: position{line: 85, col: 24, offset: 4273},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 85, col: 24, offset: 4273},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 43, offset: 4292},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 86, col: 1, offset: 4307},
			expr: &charClassMatcher{
				pos:             position{line: 86, col: 20, offset: 4328},
				val:             "['bfnrt]",
				chars:           []rune{'\'', 'b', 'f', 'n', 'r', 't'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "SingleQuote",
			pos:  position{line: 87, col: 1, offset: 4338},
			expr: &litMatcher{
				pos:        position{line: 87, col: 15, offset: 4354},
				val:        "'",
				ignoreCase: false,
			},
		},
		{
			name: "DoubleString",
			pos:  position{line: 89, col: 1, offset: 4419},
			expr: &actionExpr{
				pos: position{line: 89, col: 16, offset: 4436},
				run: (*parser).callonDoubleString1,
				expr: &seqExpr{
					pos: position{line: 89, col: 16, offset: 4436},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 89, col: 16, offset: 4436},
							name: "DoubleQuote",
						},
						&zeroOrMoreExpr{
							pos: position{line: 89, col: 28, offset: 4448},
							expr: &choiceExpr{
								pos: position{line: 89, col: 30, offset: 4450},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 89, col: 30, offset: 4450},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 89, col: 30, offset: 4450},
												expr: &ruleRefExpr{
													pos:  position{line: 89, col: 31, offset: 4451},
													name: "DoubleEscapedChar",
												},
											},
											&anyMatcher{
												line: 89, col: 49, offset: 4469,
											},
										},
									},
									&seqExpr{
										pos: position{line: 89, col: 53, offset: 4473},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 89, col: 53, offset: 4473},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 89, col: 58, offset: 4478},
												name: "DoubleEscapeSequence",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 82, offset: 4502},
							name: "DoubleQuote",
						},
					},
				},
			},
		},
		{
			name: "DoubleEscapedChar",
			pos:  position{line: 92, col: 1, offset: 4559},
			expr: &charClassMatcher{
				pos:             position{line: 92, col: 21, offset: 4581},
				val:             "[\\x00-\\x1f\"\\\\]",
				chars:           []rune{'"', '\\'},
				ranges:          []rune{'\x00', '\x1f'},
				basicLatinChars: [128]bool{true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "DoubleEscapeSequence",
			pos:  position{line: 93, col: 1, offset: 4597},
			expr: &choiceExpr{
				pos: position{line: 93, col: 24, offset: 4622},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 93, col: 24, offset: 4622},
						name: "DoubleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 93, col: 43, offset: 4641},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "DoubleCharEscape",
			pos:  position{line: 94, col: 1, offset: 4656},
			expr: &charClassMatcher{
				pos:             position{line: 94, col: 20, offset: 4677},
				val:             "[\"bfnrt]",
				chars:           []rune{'"', 'b', 'f', 'n', 'r', 't'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      false,
				inverted:        false,
			},
		},
		{
			name: "DoubleQuote",
			pos:  position{line: 95, col: 1, offset: 4687},
			expr: &litMatcher{
				pos:        position{line: 95, col: 15, offset: 4703},
				val:        "\"",
				ignoreCase: false,
			},
		},
		{
			name: "UnquotedString",
			pos:  position{line: 97, col: 1, offset: 4784},
			expr: &actionExpr{
				pos: position{line: 97, col: 18, offset: 4803},
				run: (*parser).callonUnquotedString1,
				expr: &seqExpr{
					pos: position{line: 97, col: 18, offset: 4803},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 97, col: 18, offset: 4803},
							val:        "{{",
							ignoreCase: false,
						},
						&zeroOrOneExpr{
							pos: position{line: 97, col: 23, offset: 4808},
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 23, offset: 4808},
								name: "Whitespace",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 35, offset: 4820},
							name: "UnquotedIdentifier",
						},
						&zeroOrOneExpr{
							pos: position{line: 97, col: 54, offset: 4839},
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 54, offset: 4839},
								name: "Whitespace",
							},
						},
						&litMatcher{
							pos:        position{line: 97, col: 66, offset: 4851},
							val:        "}}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "UnquotedIdentifier",
			pos:  position{line: 100, col: 1, offset: 4894},
			expr: &oneOrMoreExpr{
				pos: position{line: 100, col: 22, offset: 4917},
				expr: &charClassMatcher{
					pos:             position{line: 100, col: 22, offset: 4917},
					val:             "[0-9a-zA-Z._\\\\-]",
					chars:           []rune{'.', '_', '\\', '-'},
					ranges:          []rune{'0', '9', 'a', 'z', 'A', 'Z'},
					basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false},
					ignoreCase:      false,
					inverted:        false,
				},
			},
		},
		{
			name: "Ws",
			pos:  position{line: 102, col: 1, offset: 4965},
			expr: &ruleRefExpr{
				pos:  position{line: 102, col: 6, offset: 4972},
				name: "Whitespace",
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 103, col: 1, offset: 4984},
			expr: &actionExpr{
				pos: position{line: 103, col: 14, offset: 4999},
				run: (*parser).callonWhitespace1,
				expr: &oneOrMoreExpr{
					pos: position{line: 103, col: 14, offset: 4999},
					expr: &charClassMatcher{
						pos:             position{line: 103, col: 14, offset: 4999},
						val:             "[\\t\\n\\v\\f\\r ]",
						chars:           []rune{'\t', '\n', '\v', '\f', '\r', ' '},
						basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
						ignoreCase:      false,
						inverted:        false,
					},
				},
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 106, col: 1, offset: 5041},
			expr: &seqExpr{
				pos: position{line: 106, col: 17, offset: 5059},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 106, col: 17, offset: 5059},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 21, offset: 5063},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 30, offset: 5072},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 39, offset: 5081},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 48, offset: 5090},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 107, col: 1, offset: 5100},
			expr: &charClassMatcher{
				pos:             position{line: 107, col: 12, offset: 5113},
				val:             "[0-9a-f]i",
				ranges:          []rune{'0', '9', 'a', 'f'},
				basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
				ignoreCase:      true,
				inverted:        false,
			},
		},
		{
			name: "NumberVal",
			pos:  position{line: 111, col: 1, offset: 5230},
			expr: &choiceExpr{
				pos: position{line: 111, col: 13, offset: 5244},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 111, col: 13, offset: 5244},
						name: "ZeroErr",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 23, offset: 5254},
						name: "FloatVal",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 34, offset: 5265},
						name: "IntegerVal",
					},
				},
			},
		},
		{
			name: "FloatVal",
			pos:  position{line: 112, col: 1, offset: 5277},
			expr: &actionExpr{
				pos: position{line: 112, col: 12, offset: 5290},
				run: (*parser).callonFloatVal1,
				expr: &labeledExpr{
					pos:   position{line: 112, col: 12, offset: 5290},
					label: "flt",
					expr: &ruleRefExpr{
						pos:  position{line: 112, col: 16, offset: 5294},
						name: "Float",
					},
				},
			},
		},
		{
			name: "IntegerVal",
			pos:  position{line: 115, col: 1, offset: 5366},
			expr: &actionExpr{
				pos: position{line: 115, col: 14, offset: 5381},
				run: (*parser).callonIntegerVal1,
				expr: &labeledExpr{
					pos:   position{line: 115, col: 14, offset: 5381},
					label: "itg",
					expr: &choiceExpr{
						pos: position{line: 115, col: 19, offset: 5386},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 115, col: 19, offset: 5386},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 115, col: 29, offset: 5396},
								name: "ZeroVal",
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 121, col: 1, offset: 5548},
			expr: &choiceExpr{
				pos: position{line: 121, col: 10, offset: 5559},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 121, col: 10, offset: 5559},
						name: "ZeroErr",
					},
					&ruleRefExpr{
						pos:  position{line: 121, col: 20, offset: 5569},
						name: "Float",
					},
					&ruleRefExpr{
						pos:  position{line: 121, col: 28, offset: 5577},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 121, col: 38, offset: 5587},
						name: "ZeroVal",
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 122, col: 1, offset: 5596},
			expr: &actionExpr{
				pos: position{line: 122, col: 9, offset: 5606},
				run: (*parser).callonFloat1,
				expr: &seqExpr{
					pos: position{line: 122, col: 9, offset: 5606},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 122, col: 9, offset: 5606},
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 9, offset: 5606},
								name: "Neg",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 122, col: 14, offset: 5611},
							name: "Flt",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 126, col: 1, offset: 5722},
			expr: &actionExpr{
				pos: position{line: 126, col: 11, offset: 5734},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 126, col: 11, offset: 5734},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 126, col: 11, offset: 5734},
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 11, offset: 5734},
								name: "Neg",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 126, col: 16, offset: 5739},
							name: "Int",
						},
					},
				},
			},
		},
		{
			name: "Flt",
			pos:  position{line: 130, col: 1, offset: 5841},
			expr: &choiceExpr{
				pos: position{line: 130, col: 7, offset: 5849},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 130, col: 7, offset: 5849},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 130, col: 7, offset: 5849},
								name: "Int",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 11, offset: 5853},
								name: "Dot",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 15, offset: 5857},
								name: "Int",
							},
						},
					},
					&seqExpr{
						pos: position{line: 130, col: 21, offset: 5863},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 130, col: 21, offset: 5863},
								name: "Int",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 25, offset: 5867},
								name: "Dot",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 29, offset: 5871},
								name: "ZeroStr",
							},
						},
					},
					&seqExpr{
						pos: position{line: 130, col: 39, offset: 5881},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 130, col: 39, offset: 5881},
								name: "ZeroStr",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 47, offset: 5889},
								name: "Dot",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 51, offset: 5893},
								name: "Int",
							},
						},
					},
					&seqExpr{
						pos: position{line: 130, col: 57, offset: 5899},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 130, col: 57, offset: 5899},
								name: "ZeroStr",
							},
							&ruleRefExpr{
								pos:  position{line: 130, col: 65, offset: 5907},
								name: "Dot",
							},
						},
					},
					&actionExpr{
						pos: position{line: 130, col: 71, offset: 5913},
						run: (*parser).callonFlt17,
						expr: &seqExpr{
							pos: position{line: 130, col: 71, offset: 5913},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 130, col: 71, offset: 5913},
									name: "Int",
								},
								&ruleRefExpr{
									pos:  position{line: 130, col: 75, offset: 5917},
									name: "Dot",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Int",
			pos:  position{line: 134, col: 1, offset: 6013},
			expr: &actionExpr{
				pos: position{line: 134, col: 7, offset: 6021},
				run: (*parser).callonInt1,
				expr: &seqExpr{
					pos: position{line: 134, col: 7, offset: 6021},
					exprs: []interface{}{
						&charClassMatcher{
							pos:             position{line: 134, col: 7, offset: 6021},
							val:             "[1-9]",
							ranges:          []rune{'1', '9'},
							basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
							ignoreCase:      false,
							inverted:        false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 134, col: 12, offset: 6026},
							expr: &charClassMatcher{
								pos:             position{line: 134, col: 12, offset: 6026},
								val:             "[0-9]",
								ranges:          []rune{'0', '9'},
								basicLatinChars: [128]bool{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
								ignoreCase:      false,
								inverted:        false,
							},
						},
					},
				},
			},
		},
		{
			name: "ZeroStr",
			pos:  position{line: 138, col: 1, offset: 6098},
			expr: &actionExpr{
				pos: position{line: 138, col: 11, offset: 6110},
				run: (*parser).callonZeroStr1,
				expr: &litMatcher{
					pos:        position{line: 138, col: 11, offset: 6110},
					val:        "0",
					ignoreCase: false,
				},
			},
		},
		{
			name: "ZeroVal",
			pos:  position{line: 141, col: 1, offset: 6141},
			expr: &actionExpr{
				pos: position{line: 141, col: 11, offset: 6153},
				run: (*parser).callonZeroVal1,
				expr: &litMatcher{
					pos:        position{line: 141, col: 11, offset: 6153},
					val:        "0",
					ignoreCase: false,
				},
			},
		},
		{
			name: "ZeroErr",
			pos:  position{line: 144, col: 1, offset: 6189},
			expr: &actionExpr{
				pos: position{line: 144, col: 11, offset: 6201},
				run: (*parser).callonZeroErr1,
				expr: &seqExpr{
					pos: position{line: 144, col: 11, offset: 6201},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 144, col: 11, offset: 6201},
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 11, offset: 6201},
								name: "Neg",
							},
						},
						&litMatcher{
							pos:        position{line: 144, col: 16, offset: 6206},
							val:        "0.0",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Dot",
			pos:  position{line: 147, col: 1, offset: 6261},
			expr: &litMatcher{
				pos:        position{line: 147, col: 7, offset: 6269},
				val:        ".",
				ignoreCase: false,
			},
		},
		{
			name: "Neg",
			pos:  position{line: 148, col: 1, offset: 6274},
			expr: &litMatcher{
				pos:        position{line: 148, col: 7, offset: 6282},
				val:        "-",
				ignoreCase: false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 151, col: 1, offset: 6310},
			expr: &notExpr{
				pos: position{line: 151, col: 7, offset: 6318},
				expr: &anyMatcher{
					line: 151, col: 8, offset: 6319,
				},
			},
		},
	},
}

func (c *current) onPredNumericEqual1(left, right interface{}) (interface{}, error) {

	return PredNumericOp{t: PredTypeNumberEqual, left: left.(Valueable), right: right.(Valueable)}, nil
}

func (p *parser) callonPredNumericEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredNumericEqual1(stack["left"], stack["right"])
}

func (c *current) onPredNumericNotEqual1(left, right interface{}) (interface{}, error) {

	return PredNotOp{v: PredNumericOp{t: PredTypeNumberEqual, left: left.(Valueable), right: right.(Valueable)}}, nil
}

func (p *parser) callonPredNumericNotEqual1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredNumericNotEqual1(stack["left"], stack["right"])
}

func (c *current) onPredBoolNotEqual2(left interface{}) (interface{}, error) {

	return PredNotOp{v: PredBoolCheckOp{t: PredTypeNilCheck, v: left.(Valueable)}}, nil
}

func (p *parser) callonPredBoolNotEqual2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolNotEqual2(stack["left"])
}

func (c *current) onPredBoolNotEqual14(left interface{}) (interface{}, error) {

	return PredNotOp{v: PredBoolCheckOp{t: PredTypeTrueCheck, v: left.(Valueable)}}, nil
}

func (p *parser) callonPredBoolNotEqual14() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolNotEqual14(stack["left"])
}

func (c *current) onPredBoolNotEqual24(left interface{}) (interface{}, error) {

	return PredNotOp{v: PredBoolCheckOp{t: PredTypeFalseCheck, v: left.(Valueable)}}, nil
}

func (p *parser) callonPredBoolNotEqual24() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolNotEqual24(stack["left"])
}

func (c *current) onPredBoolEqual2(left interface{}) (interface{}, error) {

	return PredBoolCheckOp{t: PredTypeNilCheck, v: left.(Valueable)}, nil
}

func (p *parser) callonPredBoolEqual2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolEqual2(stack["left"])
}

func (c *current) onPredBoolEqual14(left interface{}) (interface{}, error) {

	return PredBoolCheckOp{t: PredTypeTrueCheck, v: left.(Valueable)}, nil
}

func (p *parser) callonPredBoolEqual14() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolEqual14(stack["left"])
}

func (c *current) onPredBoolEqual24(left interface{}) (interface{}, error) {

	return PredBoolCheckOp{t: PredTypeFalseCheck, v: left.(Valueable)}, nil
}

func (p *parser) callonPredBoolEqual24() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolEqual24(stack["left"])
}

func (c *current) onPredNumericWrongTypes1(cmbn interface{}) (interface{}, error) {

	// TODO: cmbn is an annoying []interface{} of []interface{}, make a helper to parse out the message more cleanly
	return nil, errors.New(fmt.Sprintf("an operation involving '%s' may only have numbers or singular template references as its arguments", opStringer(cmbn.([]interface{}))))
}

func (p *parser) callonPredNumericWrongTypes1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredNumericWrongTypes1(stack["cmbn"])
}

func (c *current) onPredBoolWrongTypes1(op interface{}) (interface{}, error) {

	return nil, errors.New(fmt.Sprintf("an operation involving '%s' may only have ar singular template references as its arguments left hand argument and NULL, TRUE or FALSE as it's right hand side", op.(string)))
}

func (p *parser) callonPredBoolWrongTypes1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPredBoolWrongTypes1(stack["op"])
}

func (c *current) onLVTrue1() (interface{}, error) {

	return Val{typ: ValTypeBool, bl: true}, nil
}

func (p *parser) callonLVTrue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLVTrue1()
}

func (c *current) onLVFalse1() (interface{}, error) {

	return Val{typ: ValTypeBool, bl: false}, nil
}

func (p *parser) callonLVFalse1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLVFalse1()
}

func (c *current) onLVNull1() (interface{}, error) {

	return Val{typ: ValTypeNil}, nil
}

func (p *parser) callonLVNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLVNull1()
}

func (c *current) onLVNil1() (interface{}, error) {

	return Val{typ: ValTypeNil}, nil
}

func (p *parser) callonLVNil1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLVNil1()
}

func (c *current) onTemplateVal1(str interface{}) (interface{}, error) {

	return Val{typ: ValTypeTemplate, str: str.(string)}, nil
}

func (p *parser) callonTemplateVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTemplateVal1(stack["str"])
}

func (c *current) onStringVal1(str interface{}) (interface{}, error) {

	if ok, _ := hasTemplate(str.(string)); ok {
		return Val{typ: ValTypeTemplate, str: str.(string)}, nil
	} else {
		return Val{typ: ValTypeString, str: str.(string)}, nil
	}
}

func (p *parser) callonStringVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringVal1(stack["str"])
}

func (c *current) onSingleString1(chr interface{}) (interface{}, error) {

	return strunquote(string(c.text))
}

func (p *parser) callonSingleString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleString1(stack["chr"])
}

func (c *current) onDoubleString1() (interface{}, error) {

	return strunquote(string(c.text))
}

func (p *parser) callonDoubleString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleString1()
}

func (c *current) onUnquotedString1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonUnquotedString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnquotedString1()
}

func (c *current) onWhitespace1() (interface{}, error) {

	return " ", nil
}

func (p *parser) callonWhitespace1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhitespace1()
}

func (c *current) onFloatVal1(flt interface{}) (interface{}, error) {

	return Val{typ: ValTypeFloat, flt: flt.(float64)}, nil
}

func (p *parser) callonFloatVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatVal1(stack["flt"])
}

func (c *current) onIntegerVal1(itg interface{}) (interface{}, error) {

	return Val{typ: ValTypeInt, itg: itg.(int64)}, nil
}

func (p *parser) callonIntegerVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntegerVal1(stack["itg"])
}

func (c *current) onFloat1() (interface{}, error) {

	fmt.Printf("Float capturing '%s'\n", c.text)
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonFloat1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onInteger1() (interface{}, error) {

	fmt.Printf("Integer capturing\n")
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onFlt17() (interface{}, error) {

	fmt.Printf("Flt capturing\n")
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonFlt17() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFlt17()
}

func (c *current) onInt1() (interface{}, error) {

	fmt.Printf("Int capturing\n")
	return c.text, nil
}

func (p *parser) callonInt1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInt1()
}

func (c *current) onZeroStr1() (interface{}, error) {

	return "0", nil
}

func (p *parser) callonZeroStr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onZeroStr1()
}

func (c *current) onZeroVal1() (interface{}, error) {

	return int64(0), nil
}

func (p *parser) callonZeroVal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onZeroVal1()
}

func (c *current) onZeroErr1() (interface{}, error) {

	return nil, errors.New("Invalid 0.0")
}

func (p *parser) callonZeroErr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onZeroErr1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	if cur < 128 {
		if chr.basicLatinChars[cur] != chr.inverted {
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
