// Code generated by goyacc - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import (
	"fmt"
	"github.com/microspector/microspector/pkg/templating"
	"strings"
)

type yySymType struct {
	yys      int
	val      interface{}
	vals     []interface{}
	str      string
	integer  int64
	boolean  bool
	bytes    []byte
	cmd      Command
	variable struct {
		name  string
		value interface{}
	}
	http_command_params []HttpCommandParam
	http_command_param  HttpCommandParam
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault  = 57402
	yyEofCode  = 57344
	AND        = 57392
	ASSERT     = 57361
	ASYNC      = 57365
	BODY       = 57376
	CMD        = 57364
	CONNECT    = 57371
	CONTAIN    = 57388
	CONTAINS   = 57387
	DEBUG      = 57359
	DELETE     = 57370
	END        = 57360
	EOF        = 57347
	EOL        = 57346
	EQUAL      = 57380
	EQUALS     = 57379
	FALSE      = 57352
	FLOAT      = 57350
	FOLLOW     = 57377
	GE         = 57384
	GET        = 57366
	GT         = 57383
	HEAD       = 57367
	HEADER     = 57375
	HTTP       = 57356
	IDENTIFIER = 57400
	INCLUDE    = 57362
	INTEGER    = 57349
	INTO       = 57399
	IS         = 57396
	ISNOT      = 57397
	KEYWORD    = 57354
	LE         = 57386
	LT         = 57385
	MATCH      = 57395
	MATCHES    = 57394
	MUST       = 57357
	NOFOLLOW   = 57378
	NOT        = 57398
	NOTEQUAL   = 57382
	NOTEQUALS  = 57381
	NULL       = 57353
	OPTIONS    = 57372
	OR         = 57393
	PATCH      = 57374
	POST       = 57368
	PUT        = 57369
	SET        = 57355
	SHOULD     = 57358
	SLEEP      = 57363
	STARTSWITH = 57389
	STARTWITH  = 57390
	STRING     = 57348
	TRACE      = 57373
	TRUE       = 57351
	TYPE       = 57401
	WHEN       = 57391
	yyErrCode  = 57345

	yyMaxDepth = 200
	yyTabOfs   = -118
)

var (
	yyPrec = map[int]int{
		'|': 0,
		'&': 1,
		'+': 2,
		'-': 2,
		'*': 3,
		'/': 3,
		'%': 3,
	}

	yyXLAT = map[int]int{
		57400: 0,   // IDENTIFIER (121x)
		123:   1,   // '{' (120x)
		36:    2,   // '$' (119x)
		57348: 3,   // STRING (113x)
		57361: 4,   // ASSERT (91x)
		57364: 5,   // CMD (91x)
		57359: 6,   // DEBUG (91x)
		57360: 7,   // END (91x)
		57356: 8,   // HTTP (91x)
		57362: 9,   // INCLUDE (91x)
		57357: 10,  // MUST (91x)
		57355: 11,  // SET (91x)
		57358: 12,  // SHOULD (91x)
		57363: 13,  // SLEEP (91x)
		57344: 14,  // $end (90x)
		57365: 15,  // ASYNC (90x)
		45:    16,  // '-' (85x)
		57391: 17,  // WHEN (84x)
		57399: 18,  // INTO (82x)
		91:    19,  // '[' (68x)
		57350: 20,  // FLOAT (68x)
		57349: 21,  // INTEGER (68x)
		57353: 22,  // NULL (68x)
		57401: 23,  // TYPE (68x)
		57392: 24,  // AND (49x)
		57393: 25,  // OR (49x)
		41:    26,  // ')' (47x)
		33:    27,  // '!' (45x)
		57398: 28,  // NOT (45x)
		40:    29,  // '(' (44x)
		57431: 30,  // variable (41x)
		57352: 31,  // FALSE (36x)
		57351: 32,  // TRUE (36x)
		37:    33,  // '%' (33x)
		42:    34,  // '*' (33x)
		43:    35,  // '+' (33x)
		47:    36,  // '/' (33x)
		57404: 37,  // any_value (31x)
		57405: 38,  // array (31x)
		57416: 39,  // func_call (31x)
		57388: 40,  // CONTAIN (30x)
		57387: 41,  // CONTAINS (30x)
		57380: 42,  // EQUAL (30x)
		57379: 43,  // EQUALS (30x)
		57384: 44,  // GE (30x)
		57383: 45,  // GT (30x)
		57396: 46,  // IS (30x)
		57397: 47,  // ISNOT (30x)
		57386: 48,  // LE (30x)
		57385: 49,  // LT (30x)
		57395: 50,  // MATCH (30x)
		57394: 51,  // MATCHES (30x)
		57382: 52,  // NOTEQUAL (30x)
		57381: 53,  // NOTEQUALS (30x)
		57389: 54,  // STARTSWITH (30x)
		57390: 55,  // STARTWITH (30x)
		57376: 56,  // BODY (28x)
		57377: 57,  // FOLLOW (28x)
		57375: 58,  // HEADER (28x)
		57378: 59,  // NOFOLLOW (28x)
		57414: 60,  // expr (22x)
		44:    61,  // ',' (20x)
		93:    62,  // ']' (20x)
		57430: 63,  // true_false (15x)
		57407: 64,  // boolean_exp (14x)
		57415: 65,  // expr_opr (14x)
		57425: 66,  // operator (6x)
		57429: 67,  // string_var (6x)
		125:   68,  // '}' (2x)
		57406: 69,  // assert_command (2x)
		57408: 70,  // cmd_command (2x)
		57409: 71,  // comma_separated_values (2x)
		57410: 72,  // command (2x)
		57412: 73,  // debug_command (2x)
		57413: 74,  // end_command (2x)
		57417: 75,  // http_command (2x)
		57418: 76,  // http_command_param (2x)
		57421: 77,  // include_command (2x)
		57424: 78,  // must_command (2x)
		57426: 79,  // set_command (2x)
		57427: 80,  // should_command (2x)
		57428: 81,  // sleep_command (2x)
		57403: 82,  // any_command (1x)
		57411: 83,  // command_with_condition_opt (1x)
		57371: 84,  // CONNECT (1x)
		57370: 85,  // DELETE (1x)
		57366: 86,  // GET (1x)
		57367: 87,  // HEAD (1x)
		57419: 88,  // http_command_params (1x)
		57420: 89,  // http_method (1x)
		57422: 90,  // multi_any_value (1x)
		57423: 91,  // multi_variable (1x)
		57372: 92,  // OPTIONS (1x)
		57374: 93,  // PATCH (1x)
		57368: 94,  // POST (1x)
		57369: 95,  // PUT (1x)
		57373: 96,  // TRACE (1x)
		57402: 97,  // $default (0x)
		38:    98,  // '&' (0x)
		124:   99,  // '|' (0x)
		57347: 100, // EOF (0x)
		57346: 101, // EOL (0x)
		57345: 102, // error (0x)
		57354: 103, // KEYWORD (0x)
	}

	yySymNames = []string{
		"IDENTIFIER",
		"'{'",
		"'$'",
		"STRING",
		"ASSERT",
		"CMD",
		"DEBUG",
		"END",
		"HTTP",
		"INCLUDE",
		"MUST",
		"SET",
		"SHOULD",
		"SLEEP",
		"$end",
		"ASYNC",
		"'-'",
		"WHEN",
		"INTO",
		"'['",
		"FLOAT",
		"INTEGER",
		"NULL",
		"TYPE",
		"AND",
		"OR",
		"')'",
		"'!'",
		"NOT",
		"'('",
		"variable",
		"FALSE",
		"TRUE",
		"'%'",
		"'*'",
		"'+'",
		"'/'",
		"any_value",
		"array",
		"func_call",
		"CONTAIN",
		"CONTAINS",
		"EQUAL",
		"EQUALS",
		"GE",
		"GT",
		"IS",
		"ISNOT",
		"LE",
		"LT",
		"MATCH",
		"MATCHES",
		"NOTEQUAL",
		"NOTEQUALS",
		"STARTSWITH",
		"STARTWITH",
		"BODY",
		"FOLLOW",
		"HEADER",
		"NOFOLLOW",
		"expr",
		"','",
		"']'",
		"true_false",
		"boolean_exp",
		"expr_opr",
		"operator",
		"string_var",
		"'}'",
		"assert_command",
		"cmd_command",
		"comma_separated_values",
		"command",
		"debug_command",
		"end_command",
		"http_command",
		"http_command_param",
		"include_command",
		"must_command",
		"set_command",
		"should_command",
		"sleep_command",
		"any_command",
		"command_with_condition_opt",
		"CONNECT",
		"DELETE",
		"GET",
		"HEAD",
		"http_command_params",
		"http_method",
		"multi_any_value",
		"multi_variable",
		"OPTIONS",
		"PATCH",
		"POST",
		"PUT",
		"TRACE",
		"$default",
		"'&'",
		"'|'",
		"EOF",
		"EOL",
		"error",
		"KEYWORD",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {82, 0},
		2:   {82, 2},
		3:   {83, 5},
		4:   {83, 3},
		5:   {83, 3},
		6:   {83, 1},
		7:   {83, 2},
		8:   {83, 4},
		9:   {72, 1},
		10:  {72, 1},
		11:  {72, 1},
		12:  {72, 1},
		13:  {72, 1},
		14:  {72, 1},
		15:  {72, 1},
		16:  {72, 1},
		17:  {72, 1},
		18:  {72, 1},
		19:  {81, 2},
		20:  {77, 2},
		21:  {73, 2},
		22:  {70, 2},
		23:  {70, 2},
		24:  {74, 3},
		25:  {74, 2},
		26:  {74, 1},
		27:  {69, 2},
		28:  {69, 2},
		29:  {78, 2},
		30:  {78, 2},
		31:  {80, 2},
		32:  {80, 2},
		33:  {79, 3},
		34:  {79, 3},
		35:  {79, 3},
		36:  {75, 4},
		37:  {75, 3},
		38:  {88, 1},
		39:  {88, 2},
		40:  {76, 2},
		41:  {76, 2},
		42:  {76, 2},
		43:  {76, 1},
		44:  {76, 1},
		45:  {89, 1},
		46:  {89, 1},
		47:  {89, 1},
		48:  {89, 1},
		49:  {89, 1},
		50:  {89, 1},
		51:  {89, 1},
		52:  {89, 1},
		53:  {89, 1},
		54:  {91, 1},
		55:  {91, 2},
		56:  {90, 1},
		57:  {90, 2},
		58:  {37, 1},
		59:  {37, 1},
		60:  {37, 1},
		61:  {37, 1},
		62:  {37, 1},
		63:  {37, 1},
		64:  {37, 1},
		65:  {37, 2},
		66:  {37, 1},
		67:  {30, 5},
		68:  {30, 2},
		69:  {30, 1},
		70:  {66, 1},
		71:  {66, 1},
		72:  {66, 1},
		73:  {66, 1},
		74:  {66, 1},
		75:  {66, 1},
		76:  {66, 1},
		77:  {66, 1},
		78:  {66, 1},
		79:  {66, 1},
		80:  {66, 1},
		81:  {66, 1},
		82:  {66, 1},
		83:  {66, 1},
		84:  {66, 1},
		85:  {66, 1},
		86:  {66, 2},
		87:  {66, 2},
		88:  {64, 3},
		89:  {64, 1},
		90:  {64, 3},
		91:  {64, 3},
		92:  {64, 1},
		93:  {64, 2},
		94:  {64, 2},
		95:  {63, 1},
		96:  {63, 1},
		97:  {65, 3},
		98:  {65, 3},
		99:  {65, 3},
		100: {65, 3},
		101: {65, 3},
		102: {65, 3},
		103: {67, 1},
		104: {67, 1},
		105: {60, 3},
		106: {60, 3},
		107: {60, 3},
		108: {60, 3},
		109: {60, 3},
		110: {60, 3},
		111: {60, 1},
		112: {39, 3},
		113: {39, 4},
		114: {38, 2},
		115: {38, 3},
		116: {71, 1},
		117: {71, 3},
	}

	yyXErrors = map[yyXError]string{
		{36, -1}:  "expected '{'",
		{43, -1}:  "expected '}'",
		{44, -1}:  "expected '}'",
		{37, -1}:  "expected IDENTIFIER",
		{42, -1}:  "expected IDENTIFIER",
		{0, -1}:   "expected any_command or one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP]",
		{110, -1}: "expected any_value or expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{134, -1}: "expected any_value or expr or true_false or one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{18, -1}:  "expected any_value or multi_any_value or one of ['$', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{50, -1}:  "expected any_value or one of [$end, '$', '-', '[', '{', ASSERT, ASYNC, BODY, CMD, DEBUG, END, FLOAT, FOLLOW, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NOFOLLOW, NULL, SET, SHOULD, SLEEP, STRING, TYPE, WHEN]",
		{150, -1}: "expected any_value or one of [$end, '$', '-', '[', '{', ASSERT, ASYNC, CMD, DEBUG, END, FLOAT, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NULL, SET, SHOULD, SLEEP, STRING, TYPE, WHEN]",
		{15, -1}:  "expected any_value or one of ['$', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{16, -1}:  "expected any_value or one of ['$', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{60, -1}:  "expected any_value or one of ['$', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{68, -1}:  "expected any_value or one of ['$', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{78, -1}:  "expected array or boolean_exp or expr or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{82, -1}:  "expected boolean_exp or expr or expr_opr or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{19, -1}:  "expected boolean_exp or one of [$end, '!', '$', '(', '-', '[', '{', ASSERT, ASYNC, CMD, DEBUG, END, FALSE, FLOAT, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NOT, NULL, SET, SHOULD, SLEEP, STRING, TRUE, TYPE, WHEN]",
		{20, -1}:  "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{21, -1}:  "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{22, -1}:  "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{86, -1}:  "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{87, -1}:  "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{129, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{130, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{146, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{161, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{164, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{167, -1}: "expected boolean_exp or one of ['!', '$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NOT, NULL, STRING, TRUE, TYPE]",
		{70, -1}:  "expected comma_separated_values or one of ['$', ')', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{63, -1}:  "expected comma_separated_values or one of ['$', '-', '[', ']', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{4, -1}:   "expected command or one of [ASSERT, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP]",
		{1, -1}:   "expected command_with_condition_opt or one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP]",
		{111, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{112, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{113, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{114, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{115, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{116, -1}: "expected expr or one of ['$', '(', '-', '[', '{', FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TYPE]",
		{46, -1}:  "expected http_command_param or one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{35, -1}:  "expected http_command_params or one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{24, -1}:  "expected http_method or one of [CONNECT, DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE]",
		{17, -1}:  "expected multi_variable or one of ['$', '{', IDENTIFIER]",
		{41, -1}:  "expected one of [$end, '!', '$', '%', '(', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FALSE, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TRUE, TYPE, WHEN]",
		{45, -1}:  "expected one of [$end, '!', '$', '%', '(', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FALSE, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TRUE, TYPE, WHEN]",
		{62, -1}:  "expected one of [$end, '!', '$', '%', '(', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{53, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{54, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{55, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{56, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{57, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{58, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{59, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{61, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{64, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{67, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{71, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{73, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{74, -1}:  "expected one of [$end, '!', '$', '%', ')', '*', '+', ',', '-', '/', '[', ']', '{', AND, ASSERT, ASYNC, BODY, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, FLOAT, FOLLOW, GE, GT, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOFOLLOW, NOT, NOTEQUAL, NOTEQUALS, NULL, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, TYPE, WHEN]",
		{117, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{118, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{120, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{121, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{122, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{123, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{124, -1}: "expected one of [$end, '!', '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, IDENTIFIER, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, OR, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, STRING, WHEN]",
		{38, -1}:  "expected one of [$end, '!', '$', '(', '-', '[', '{', ASSERT, ASYNC, BODY, CMD, DEBUG, END, FALSE, FLOAT, FOLLOW, HEADER, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NOFOLLOW, NOT, NULL, SET, SHOULD, SLEEP, STRING, TRUE, TYPE, WHEN]",
		{79, -1}:  "expected one of [$end, '!', '%', '*', '+', '-', '/', ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, WHEN]",
		{125, -1}: "expected one of [$end, '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{126, -1}: "expected one of [$end, '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{135, -1}: "expected one of [$end, '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{137, -1}: "expected one of [$end, '$', '%', ')', '*', '+', '-', '/', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{83, -1}:  "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{85, -1}:  "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{88, -1}:  "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{89, -1}:  "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{90, -1}:  "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{131, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{132, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{133, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{136, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{141, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{142, -1}: "expected one of [$end, '$', ')', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{149, -1}: "expected one of [$end, '$', '-', '[', '{', ASSERT, ASYNC, CMD, DEBUG, END, FLOAT, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NULL, SET, SHOULD, SLEEP, STRING, TYPE, WHEN]",
		{151, -1}: "expected one of [$end, '$', '-', '[', '{', ASSERT, ASYNC, CMD, DEBUG, END, FLOAT, HTTP, IDENTIFIER, INCLUDE, INTEGER, INTO, MUST, NULL, SET, SHOULD, SLEEP, STRING, TYPE, WHEN]",
		{143, -1}: "expected one of [$end, '$', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{144, -1}: "expected one of [$end, '$', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{145, -1}: "expected one of [$end, '$', '{', AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, STRING, WHEN]",
		{39, -1}:  "expected one of [$end, '$', '{', ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, STRING, WHEN]",
		{40, -1}:  "expected one of [$end, '$', '{', ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, STRING, WHEN]",
		{157, -1}: "expected one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{158, -1}: "expected one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{159, -1}: "expected one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{153, -1}: "expected one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{154, -1}: "expected one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{81, -1}:  "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, WHEN]",
		{147, -1}: "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, WHEN]",
		{148, -1}: "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, OR, SET, SHOULD, SLEEP, WHEN]",
		{162, -1}: "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, OR, SET, SHOULD, SLEEP]",
		{165, -1}: "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, OR, SET, SHOULD, SLEEP]",
		{168, -1}: "expected one of [$end, AND, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, OR, SET, SHOULD, SLEEP]",
		{47, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{51, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{52, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{75, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{76, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{77, -1}:  "expected one of [$end, ASSERT, ASYNC, BODY, CMD, DEBUG, END, FOLLOW, HEADER, HTTP, INCLUDE, INTO, MUST, NOFOLLOW, SET, SHOULD, SLEEP, WHEN]",
		{3, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{5, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{6, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{7, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{8, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{12, -1}:  "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{13, -1}:  "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{14, -1}:  "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{155, -1}: "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{156, -1}: "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{160, -1}: "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP, WHEN]",
		{166, -1}: "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP, WHEN]",
		{2, -1}:   "expected one of [$end, ASSERT, ASYNC, CMD, DEBUG, END, HTTP, INCLUDE, MUST, SET, SHOULD, SLEEP]",
		{92, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{93, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{94, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{95, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{96, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{97, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{98, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{99, -1}:  "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{100, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{101, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{102, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{103, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{104, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{105, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{106, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{107, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{127, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{128, -1}: "expected one of ['$', '(', '-', '[', '{', FALSE, FLOAT, IDENTIFIER, INTEGER, NULL, STRING, TRUE, TYPE]",
		{26, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{27, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{28, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{29, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{30, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{31, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{32, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{33, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{34, -1}:  "expected one of ['$', '{', IDENTIFIER, STRING]",
		{119, -1}: "expected one of ['%', ')', '*', '+', '-', '/']",
		{66, -1}:  "expected one of [')', ',', ']']",
		{69, -1}:  "expected one of [')', ',', ']']",
		{72, -1}:  "expected one of [')', ',']",
		{138, -1}: "expected one of [')', AND, OR]",
		{139, -1}: "expected one of [')', AND, OR]",
		{65, -1}:  "expected one of [',', ']']",
		{84, -1}:  "expected operator or one of [$end, '!', '%', ')', '*', '+', '-', '/', ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, WHEN]",
		{80, -1}:  "expected operator or one of [$end, '!', '%', '*', '+', '-', '/', ASSERT, ASYNC, CMD, CONTAIN, CONTAINS, DEBUG, END, EQUAL, EQUALS, GE, GT, HTTP, INCLUDE, INTO, IS, ISNOT, LE, LT, MATCH, MATCHES, MUST, NOT, NOTEQUAL, NOTEQUALS, SET, SHOULD, SLEEP, STARTSWITH, STARTWITH, WHEN]",
		{140, -1}: "expected operator or one of ['!', '%', ')', '*', '+', '-', '/', CONTAIN, CONTAINS, EQUAL, EQUALS, GE, GT, IS, ISNOT, LE, LT, MATCH, MATCHES, NOT, NOTEQUAL, NOTEQUALS, STARTSWITH, STARTWITH]",
		{91, -1}:  "expected operator or one of ['!', '%', '*', '+', '-', '/', CONTAIN, CONTAINS, EQUAL, EQUALS, GE, GT, IS, ISNOT, LE, LT, MATCH, MATCHES, NOT, NOTEQUAL, NOTEQUALS, STARTSWITH, STARTWITH]",
		{108, -1}: "expected operator or one of ['!', CONTAIN, CONTAINS, EQUAL, EQUALS, GE, GT, IS, ISNOT, LE, LT, MATCH, MATCHES, NOT, NOTEQUAL, NOTEQUALS, STARTSWITH, STARTWITH]",
		{109, -1}: "expected operator or one of ['!', CONTAIN, CONTAINS, EQUAL, EQUALS, GE, GT, IS, ISNOT, LE, LT, MATCH, MATCHES, NOT, NOTEQUAL, NOTEQUALS, STARTSWITH, STARTWITH]",
		{9, -1}:   "expected string_var or one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{10, -1}:  "expected string_var or one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{11, -1}:  "expected string_var or one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, STRING, WHEN]",
		{25, -1}:  "expected string_var or one of ['$', '{', IDENTIFIER, STRING]",
		{48, -1}:  "expected string_var or one of ['$', '{', IDENTIFIER, STRING]",
		{49, -1}:  "expected string_var or one of ['$', '{', IDENTIFIER, STRING]",
		{152, -1}: "expected variable or one of [$end, '$', '{', ASSERT, ASYNC, CMD, DEBUG, END, HTTP, IDENTIFIER, INCLUDE, INTO, MUST, SET, SHOULD, SLEEP, WHEN]",
		{23, -1}:  "expected variable or one of ['$', '{', IDENTIFIER]",
		{163, -1}: "expected variable or one of ['$', '{', IDENTIFIER]",
	}

	yyParseTab = [169][]uint16{
		// 0
		{4: 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 82: 119},
		{4: 138, 136, 135, 137, 142, 134, 139, 141, 140, 133, 118, 122, 69: 127, 132, 72: 121, 125, 126, 124, 77: 130, 128, 123, 129, 131, 83: 120},
		{4: 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116},
		{4: 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 17: 282, 281},
		{4: 138, 136, 135, 137, 142, 134, 139, 141, 140, 133, 69: 127, 132, 72: 278, 125, 126, 124, 77: 130, 128, 123, 129, 131},
		// 5
		{4: 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 17: 109, 109},
		{4: 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 108, 17: 108, 108},
		{4: 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 17: 107, 107},
		{4: 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 17: 106, 106},
		{156, 154, 155, 157, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 17: 105, 105, 30: 158, 67: 277},
		// 10
		{156, 154, 155, 157, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 17: 104, 104, 30: 158, 67: 276},
		{156, 154, 155, 157, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 103, 17: 103, 103, 30: 158, 67: 275},
		{4: 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 102, 17: 102, 102},
		{4: 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 17: 101, 101},
		{4: 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 17: 100, 100},
		// 15
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 274, 177, 179},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 273, 177, 179},
		{156, 154, 155, 30: 271, 91: 270},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 267, 177, 179, 90: 268},
		{180, 154, 155, 171, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 92, 178, 264, 92, 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 265, 203},
		// 20
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 263, 203},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 262, 203},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 261, 203},
		{156, 154, 155, 30: 196},
		{84: 149, 148, 144, 145, 89: 143, 92: 150, 152, 146, 147, 151},
		// 25
		{156, 154, 155, 157, 30: 158, 67: 153},
		{73, 73, 73, 73},
		{72, 72, 72, 72},
		{71, 71, 71, 71},
		{70, 70, 70, 70},
		// 30
		{69, 69, 69, 69},
		{68, 68, 68, 68},
		{67, 67, 67, 67},
		{66, 66, 66, 66},
		{65, 65, 65, 65},
		// 35
		{4: 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 17: 81, 81, 56: 167, 168, 166, 169, 76: 165, 88: 164},
		{1: 160},
		{159},
		{49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 27: 49, 49, 49, 31: 49, 49, 56: 49, 49, 49, 49},
		{15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 17: 15, 15, 56: 15, 15, 15, 15},
		// 40
		{14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 17: 14, 14, 56: 14, 14, 14, 14},
		{50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 31: 50, 50, 50, 50, 50, 50, 40: 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 61: 50, 50},
		{161},
		{68: 162},
		{68: 163},
		// 45
		{51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 31: 51, 51, 51, 51, 51, 51, 40: 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 61: 51, 51},
		{4: 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 17: 82, 82, 56: 167, 168, 166, 169, 76: 195},
		{4: 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 17: 80, 80, 56: 80, 80, 80, 80},
		{156, 154, 155, 157, 30: 158, 67: 194},
		{156, 154, 155, 157, 30: 158, 67: 193},
		// 50
		{180, 154, 155, 171, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 178, 75, 75, 181, 174, 173, 176, 175, 30: 172, 37: 170, 177, 179, 56: 75, 75, 75, 75},
		{4: 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 17: 74, 74, 56: 74, 74, 74, 74},
		{4: 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 17: 76, 76, 56: 76, 76, 76, 76},
		{60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 33: 60, 60, 60, 60, 40: 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 61: 60, 60},
		{59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 33: 59, 59, 59, 59, 40: 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 61: 59, 59},
		// 55
		{58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 33: 58, 58, 58, 58, 40: 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 61: 58, 58},
		{57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 33: 57, 57, 57, 57, 40: 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 61: 57, 57},
		{56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 33: 56, 56, 56, 56, 40: 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 61: 56, 56},
		{55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 33: 55, 55, 55, 55, 40: 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 61: 55, 55},
		{54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 33: 54, 54, 54, 54, 40: 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 61: 54, 54},
		// 60
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 192, 177, 179},
		{52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 33: 52, 52, 52, 52, 40: 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 61: 52, 52},
		{49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 188, 33: 49, 49, 49, 49, 40: 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 61: 49, 49},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 184, 177, 179, 62: 182, 71: 183},
		{4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 33: 4, 4, 4, 4, 40: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 61: 4, 4},
		// 65
		{61: 186, 185},
		{26: 2, 61: 2, 2},
		{3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 33: 3, 3, 3, 3, 40: 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 61: 3, 3},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 30: 172, 37: 187, 177, 179},
		{26: 1, 61: 1, 1},
		// 70
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 26: 189, 30: 172, 37: 184, 177, 179, 71: 190},
		{6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 33: 6, 6, 6, 6, 40: 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 61: 6, 6},
		{26: 191, 61: 186},
		{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 33: 5, 5, 5, 5, 40: 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 61: 5, 5},
		{53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 33: 53, 53, 53, 53, 40: 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 61: 53, 53},
		// 75
		{4: 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 17: 77, 77, 56: 77, 77, 77, 77},
		{4: 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 17: 78, 78, 56: 78, 78, 78, 78},
		{4: 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 17: 79, 79, 56: 79, 79, 79, 79},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 197, 179, 60: 198, 63: 201, 199, 203},
		{4: 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 54, 85, 85, 27: 54, 54, 33: 54, 54, 54, 54, 40: 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54},
		// 80
		{4: 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 230, 84, 84, 27: 227, 226, 33: 233, 231, 229, 232, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 228},
		{4: 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 17: 83, 83, 24: 247, 248},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 258, 63: 201, 256, 257},
		{29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 17: 29, 29, 24: 29, 29, 29},
		{4: 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 26: 7, 227, 226, 33: 7, 7, 7, 7, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 252},
		// 85
		{26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 17: 26, 26, 24: 26, 26, 26},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 251, 203},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 208, 203},
		{23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 17: 23, 23, 24: 23, 23, 23},
		{22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 17: 22, 22, 24: 22, 22, 22},
		// 90
		{24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 17: 24, 24, 24: 247, 248, 24},
		{16: 230, 27: 227, 226, 33: 233, 231, 229, 232, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 228},
		{48, 48, 48, 48, 16: 48, 19: 48, 48, 48, 48, 48, 29: 48, 31: 48, 48},
		{47, 47, 47, 47, 16: 47, 19: 47, 47, 47, 47, 47, 29: 47, 31: 47, 47},
		{46, 46, 46, 46, 16: 46, 19: 46, 46, 46, 46, 46, 29: 46, 31: 46, 46},
		// 95
		{45, 45, 45, 45, 16: 45, 19: 45, 45, 45, 45, 45, 29: 45, 31: 45, 45},
		{44, 44, 44, 44, 16: 44, 19: 44, 44, 44, 44, 44, 29: 44, 31: 44, 44},
		{43, 43, 43, 43, 16: 43, 19: 43, 43, 43, 43, 43, 29: 43, 31: 43, 43},
		{42, 42, 42, 42, 16: 42, 19: 42, 42, 42, 42, 42, 29: 42, 31: 42, 42},
		{41, 41, 41, 41, 16: 41, 19: 41, 41, 41, 41, 41, 29: 41, 31: 41, 41},
		// 100
		{40, 40, 40, 40, 16: 40, 19: 40, 40, 40, 40, 40, 29: 40, 31: 40, 40},
		{39, 39, 39, 39, 16: 39, 19: 39, 39, 39, 39, 39, 29: 39, 31: 39, 39},
		{38, 38, 38, 38, 16: 38, 19: 38, 38, 38, 38, 38, 29: 38, 31: 38, 38},
		{37, 37, 37, 37, 16: 37, 19: 37, 37, 37, 37, 37, 29: 37, 31: 37, 37},
		{36, 36, 36, 36, 16: 36, 19: 36, 36, 36, 36, 36, 29: 36, 31: 36, 36},
		// 105
		{35, 35, 35, 35, 16: 35, 19: 35, 35, 35, 35, 35, 29: 35, 31: 35, 35},
		{34, 34, 34, 34, 16: 34, 19: 34, 34, 34, 34, 34, 29: 34, 31: 34, 34},
		{33, 33, 33, 33, 16: 33, 19: 33, 33, 33, 33, 33, 29: 33, 31: 33, 33},
		{27: 227, 226, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 246},
		{27: 227, 226, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 245},
		// 110
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 244, 177, 179, 60: 243},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 242},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 241},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 240},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 239},
		// 115
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 235},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 37: 236, 177, 179, 60: 237},
		{8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 24: 8, 8, 8, 8, 8, 33: 8, 8, 8, 8, 40: 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8},
		{7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 24: 7, 7, 7, 7, 7, 33: 7, 7, 7, 7, 40: 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7},
		{16: 230, 26: 238, 33: 233, 231, 229, 232},
		// 120
		{13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 24: 13, 13, 13, 13, 13, 33: 13, 13, 13, 13, 40: 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13},
		{9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 24: 9, 9, 9, 9, 9, 33: 9, 9, 9, 9, 40: 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9},
		{10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 24: 10, 10, 10, 10, 10, 33: 10, 10, 10, 10, 40: 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10},
		{11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 24: 11, 11, 11, 11, 11, 33: 233, 231, 11, 232, 40: 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11},
		{12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 24: 12, 12, 12, 12, 12, 33: 233, 231, 12, 232, 40: 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12},
		// 125
		{20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 230, 20, 20, 24: 20, 20, 20, 33: 233, 231, 229, 232},
		{18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 7, 18, 18, 24: 18, 18, 18, 33: 7, 7, 7, 7},
		{31, 31, 31, 31, 16: 31, 19: 31, 31, 31, 31, 31, 29: 31, 31: 31, 31},
		{32, 32, 32, 32, 16: 32, 19: 32, 32, 32, 32, 32, 29: 32, 31: 32, 32},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 250, 203},
		// 130
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 249, 203},
		{16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17: 16, 16, 24: 247, 248, 16},
		{17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17: 17, 17, 24: 247, 248, 17},
		{25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 17: 25, 25, 24: 247, 248, 25},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 29: 234, 172, 207, 206, 37: 253, 177, 179, 60: 255, 63: 254},
		// 135
		{28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 7, 28, 28, 24: 28, 28, 28, 33: 7, 7, 7, 7},
		{27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 17: 27, 27, 24: 27, 27, 27},
		{19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 230, 19, 19, 24: 19, 19, 19, 33: 233, 231, 229, 232},
		{24: 247, 248, 260},
		{24: 26, 26, 259},
		// 140
		{16: 230, 26: 238, 227, 226, 33: 233, 231, 229, 232, 40: 219, 218, 211, 210, 215, 214, 224, 225, 217, 216, 222, 223, 213, 212, 220, 221, 66: 228},
		{21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 17: 21, 21, 24: 21, 21, 21},
		{30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 17: 30, 30, 24: 30, 30, 30},
		{86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 17: 86, 86, 24: 247, 248},
		{88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 17: 88, 88, 24: 247, 248},
		// 145
		{90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 17: 90, 90, 24: 247, 248},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 266, 203},
		{4: 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 93, 17: 93, 93, 24: 247, 248},
		{4: 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 17: 94, 94, 24: 247, 248},
		{62, 62, 62, 62, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 62, 96, 96, 62, 62, 62, 62, 62},
		// 150
		{180, 154, 155, 171, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 95, 178, 95, 95, 181, 174, 173, 176, 175, 30: 172, 37: 269, 177, 179},
		{61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61},
		{156, 154, 155, 4: 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 17: 97, 97, 30: 272},
		{64, 64, 64, 4: 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 17: 64, 64},
		{63, 63, 63, 4: 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 17: 63, 63},
		// 155
		{4: 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 17: 98, 98},
		{4: 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 17: 99, 99},
		{87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 17: 87, 87},
		{89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 17: 89, 89},
		{91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 91, 17: 91, 91},
		// 160
		{4: 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 17: 279},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 280, 203},
		{4: 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 24: 247, 248},
		{156, 154, 155, 30: 284},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 283, 203},
		// 165
		{4: 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 24: 247, 248},
		{4: 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 17: 285},
		{180, 154, 155, 171, 16: 178, 19: 181, 174, 173, 176, 175, 27: 205, 204, 200, 172, 207, 206, 37: 202, 177, 179, 60: 209, 63: 201, 286, 203},
		{4: 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 115, 24: 247, 248},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 102

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 3:
		{
			//run command put result into variable WHEN boolean_exp is true
			if strings.Contains(yyS[yypt-2].variable.name, ".") {
				yylex.Error("nested variables are not supported yet")
			}

			if yyS[yypt-0].boolean {
				yylex.(*lex).GlobalVars[yyS[yypt-2].variable.name] = yyS[yypt-4].cmd.Run(yylex.(*lex))
			}
		}
	case 4:
		{
			//command INTO variable
			if strings.Contains(yyS[yypt-0].variable.name, ".") {
				yylex.Error("nested variables are not supported yet")
			}
			yylex.(*lex).GlobalVars[yyS[yypt-0].variable.name] = yyS[yypt-2].cmd.Run(yylex.(*lex))
		}
	case 5:
		{
			//run the command only if boolean_exp is true
			if yyS[yypt-0].boolean {
				yyS[yypt-2].cmd.Run(yylex.(*lex))
			}
		}
	case 6:
		{
			//just run the command
			yyS[yypt-0].cmd.Run(yylex.(*lex))
			//run command without condition

		}
	case 7:
		{
			go yyS[yypt-0].cmd.Run(yylex.(*lex))
		}
	case 8:
		{
			//run the command only if boolean_exp is true
			if yyS[yypt-0].boolean {
				go yyS[yypt-2].cmd.Run(yylex.(*lex))
			}
		}
	case 19:
		{
			yyVAL.cmd = &SleepCommand{
				Millisecond: intVal(yyS[yypt-0].val),
			}
		}
	case 20:
		{
			yyVAL.cmd = &IncludeCommand{
				File: yyS[yypt-0].val.(string),
			}
		}
	case 21:
		{
			yyVAL.cmd = &DebugCommand{
				Values: yyS[yypt-0].vals,
			}
		}
	case 22:
		{
			yyVAL.cmd = &CmdCommand{
				Params: []interface{}{yyS[yypt-0].val},
			}
		}
	case 23:
		{
			yyVAL.cmd = &CmdCommand{
				Params: yyS[yypt-0].vals,
			}
		}
	case 24:
		{
			if yyS[yypt-0].boolean {
				return -1
			}

			yyVAL.cmd = &EndCommand{}
		}
	case 25:
		{
			if yyS[yypt-0].boolean {
				return -1
			}

			yyVAL.cmd = &EndCommand{}
		}
	case 26:
		{
			return -1
		}
	case 27:
		{
			if yyS[yypt-1].cmd.(*AssertCommand).Failed {
				yylex.(*lex).State.Assert.Messages = append(yylex.(*lex).State.Assert.Messages, yyS[yypt-0].str)
			}

			yyVAL.cmd = yyS[yypt-1].cmd
		}
	case 28:
		{
			if !yyS[yypt-0].boolean {
				yylex.(*lex).State.Assert.Failed++
			} else {
				yylex.(*lex).State.Assert.Succeeded++
			}
			yyVAL.cmd = &AssertCommand{
				Failed: !yyS[yypt-0].boolean,
			}
		}
	case 29:
		{
			if yyS[yypt-1].cmd.(*MustCommand).Failed {
				yylex.(*lex).State.Must.Messages = append(yylex.(*lex).State.Must.Messages, yyS[yypt-0].str)
			}

			yyVAL.cmd = yyS[yypt-1].cmd
		}
	case 30:
		{
			if !yyS[yypt-0].boolean {
				yylex.(*lex).State.Must.Failed++
			} else {
				yylex.(*lex).State.Must.Succeeded++
			}

			yyVAL.cmd = &MustCommand{
				Failed: !yyS[yypt-0].boolean,
			}
		}
	case 31:
		{
			if yyS[yypt-1].cmd.(*ShouldCommand).Failed {
				yylex.(*lex).State.Should.Messages = append(yylex.(*lex).State.Should.Messages, yyS[yypt-0].str)
			}

			yyVAL.cmd = yyS[yypt-1].cmd
		}
	case 32:
		{
			if !yyS[yypt-0].boolean {
				yylex.(*lex).State.Should.Failed++
			} else {
				yylex.(*lex).State.Should.Succeeded++
			}
			yyVAL.cmd = &ShouldCommand{
				Failed: !yyS[yypt-0].boolean,
			}
		}
	case 33:
		{
			yyVAL.cmd = &SetCommand{
				Name:  yyS[yypt-1].variable.name,
				Value: yyS[yypt-0].vals,
			}
		}
	case 34:
		{
			//GlobalVars[$2.name] = $3
			yyVAL.cmd = &SetCommand{
				Name:  yyS[yypt-1].variable.name,
				Value: yyS[yypt-0].val,
			}
		}
	case 35:
		{
			//GlobalVars[$2.name] = $3
			yyVAL.cmd = &SetCommand{
				Name:  yyS[yypt-1].variable.name,
				Value: yyS[yypt-0].boolean,
			}
		}
	case 36:
		{
			//call http with header here.
			yyVAL.cmd = &HttpCommand{
				Method:        yyS[yypt-2].val.(string),
				CommandParams: yyS[yypt-0].http_command_params,
				Url:           yyS[yypt-1].str,
			}
		}
	case 37:
		{
			//simple http command
			yyVAL.cmd = &HttpCommand{
				Method: yyS[yypt-1].val.(string),
				Url:    yyS[yypt-0].str,
			}
		}
	case 38:
		{
			if yyVAL.http_command_params == nil {
				yyVAL.http_command_params = make([]HttpCommandParam, 0)
			}
			yyVAL.http_command_params = append(yyVAL.http_command_params, yyS[yypt-0].http_command_param)
		}
	case 39:
		{
			if yyVAL.http_command_params == nil {
				yyVAL.http_command_params = make([]HttpCommandParam, 0)
			}

			yyVAL.http_command_params = append(yyVAL.http_command_params, yyS[yypt-0].http_command_param)
		}
	case 40:
		{
			//addin header
			yyVAL.http_command_param = HttpCommandParam{
				ParamName:  yyS[yypt-1].val.(string),
				ParamValue: yyS[yypt-0].str,
			}
		}
	case 41:
		{
			yyVAL.http_command_param = HttpCommandParam{
				ParamName:  yyS[yypt-1].val.(string),
				ParamValue: yyS[yypt-0].str,
			}
		}
	case 42:
		{
			yyVAL.http_command_param = HttpCommandParam{
				ParamName:  yyS[yypt-1].val.(string),
				ParamValue: IsTrue(yyS[yypt-0].val),
			}
		}
	case 43:
		{
			yyVAL.http_command_param = HttpCommandParam{
				ParamName:  yyS[yypt-0].val.(string),
				ParamValue: true,
			}
		}
	case 44:
		{
			yyVAL.http_command_param = HttpCommandParam{
				ParamName:  "FOLLOW",
				ParamValue: false,
			}
		}
	case 54:
		{
			//getting a single value from multi_value exp
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].variable)
		}
	case 55:
		{
			//multi value
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].variable)
		}
	case 56:
		{
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].val)
		}
	case 57:
		{
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].val)
		}
	case 58:
		{
			//string_or_var : STRING
			if isTemplate(yyS[yypt-0].val.(string)) {
				yyVAL.val, _ = templating.ExecuteTemplate(yyS[yypt-0].val.(string), yylex.(*lex).GlobalVars)
			} else {
				yyVAL.val = yyS[yypt-0].val.(string)
			}
		}
	case 59:
		{
			//any_value : variable
			switch yyS[yypt-0].variable.value.(type) {
			case string:
				if isTemplate(yyS[yypt-0].variable.value.(string)) {
					yyVAL.val, _ = templating.ExecuteTemplate(yyS[yypt-0].variable.value.(string), yylex.(*lex).GlobalVars)
				} else {
					yyVAL.val = yyS[yypt-0].variable.value
				}
			default:
				yyVAL.val = yyS[yypt-0].variable.value
			}

		}
	case 60:
		{
			//number: INTEGER
			yyVAL.val = yyS[yypt-0].val
		}
	case 61:
		{
			//number: FLOAT
			yyVAL.val = yyS[yypt-0].val
		}
	case 63:
		{
			yyVAL.val = nil
		}
	case 64:
		{
			yyVAL.val = yyS[yypt-0].vals
		}
	case 65:
		{
			yyVAL.val, _ = umin(yyS[yypt-0].val)
		}
	case 66:
		{
			yyVAL.val = yyS[yypt-0].val
		}
	case 67:
		{
			//getting variable
			yyVAL.variable.name = yyS[yypt-2].val.(string)
			yyVAL.variable.value = query(yyS[yypt-2].val.(string), yylex.(*lex).GlobalVars)
		}
	case 68:
		{
			yyVAL.variable.name = yyS[yypt-0].val.(string)
			yyVAL.variable.value = query(yyS[yypt-0].val.(string), yylex.(*lex).GlobalVars)
		}
	case 69:
		{
			yyVAL.variable.name = yyS[yypt-0].val.(string)
			yyVAL.variable.value = query(yyS[yypt-0].val.(string), yylex.(*lex).GlobalVars)
		}
	case 86:
		{
			yyVAL.val = "NOT" + yyS[yypt-0].val.(string)
		}
	case 87:
		{
			yyVAL.val = "NOT" + yyS[yypt-0].val.(string)
		}
	case 88:
		{
			//boolean_ex: '(' boolean_exp ')'
			yyVAL.boolean = yyS[yypt-1].boolean
		}
	case 90:
		{
			//boolean_ex: any_value operator any_value, oh conflicts start here :(
			operator_result := runop(yyS[yypt-2].val, yyS[yypt-1].val, yyS[yypt-0].val)
			yyVAL.boolean = operator_result
		}
	case 91:
		{
			//boolean_ex: any_value operator any_value, oh conflicts start here :(
			operator_result := runop(yyS[yypt-2].val, yyS[yypt-1].val, yyS[yypt-0].boolean)
			yyVAL.boolean = operator_result
		}
	case 93:
		{
			yyVAL.boolean = !yyS[yypt-0].boolean
		}
	case 94:
		{
			yyVAL.boolean = !yyS[yypt-0].boolean
		}
	case 95:
		{
			yyVAL.boolean = true
		}
	case 96:
		{
			yyVAL.boolean = false
		}
	case 97:
		{
			yyVAL.boolean = yyS[yypt-1].boolean
		}
	case 98:
		{
			operator_result := runop(yyS[yypt-2].val, yyS[yypt-1].val, yyS[yypt-0].val)
			yyVAL.boolean = operator_result
		}
	case 99:
		{
			operator_result := runop(yyS[yypt-2].val, yyS[yypt-1].val, yyS[yypt-0].val)
			yyVAL.boolean = operator_result
		}
	case 100:
		{
			operator_result := runop(yyS[yypt-2].val, yyS[yypt-1].val, yyS[yypt-0].val)
			yyVAL.boolean = operator_result
		}
	case 101:
		{
			//boolean_ex: boolean_exp AND boolean_exp
			yyVAL.boolean = yyS[yypt-2].boolean && yyS[yypt-0].boolean
		}
	case 102:
		{
			//boolean_ex: boolean_exp OR boolean_exp
			yyVAL.boolean = yyS[yypt-2].boolean || yyS[yypt-0].boolean
		}
	case 103:
		{
			//string_var : STRING
			if isTemplate(yyS[yypt-0].val.(string)) {
				yyVAL.str, _ = templating.ExecuteTemplate(yyS[yypt-0].val.(string), yylex.(*lex).GlobalVars)
			} else {
				yyVAL.str = yyS[yypt-0].val.(string)
			}
		}
	case 104:
		{
			//string_var : variable
			switch yyS[yypt-0].variable.value.(type) {
			case string:
				if isTemplate(yyS[yypt-0].variable.value.(string)) {
					yyVAL.str, _ = templating.ExecuteTemplate(yyS[yypt-0].variable.value.(string), yylex.(*lex).GlobalVars)
				} else {
					yyVAL.str = yyS[yypt-0].variable.value.(string)
				}
			default:
				yyVAL.str = fmt.Sprintf("%s", yyS[yypt-0].variable.value)
			}

		}
	case 105:
		{
			yyVAL.val = yyS[yypt-1].val
		}
	case 106:
		{
			yyVAL.val, _ = add(yyS[yypt-2].val, yyS[yypt-0].val)
		}
	case 107:
		{
			yyVAL.val, _ = subtract(yyS[yypt-0].val, yyS[yypt-2].val)
		}
	case 108:
		{
			yyVAL.val, _ = multiply(yyS[yypt-0].val, yyS[yypt-2].val)
		}
	case 109:
		{
			yyVAL.val, _ = divide(yyS[yypt-0].val, yyS[yypt-2].val)
		}
	case 110:
		{
			yyVAL.val, _ = mod(yyS[yypt-0].val, yyS[yypt-2].val)
		}
	case 112:
		{
			//call $1
			yyVAL.val = funcCall(yyS[yypt-2].val.(string), nil)
		}
	case 113:
		{
			yyVAL.val = funcCall(yyS[yypt-3].val.(string), yyS[yypt-1].vals)
		}
	case 114:
		{
			yyVAL.vals = make([]interface{}, 0)
		}
	case 115:
		{
			yyVAL.vals = yyS[yypt-1].vals
		}
	case 116:
		{
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].val)
		}
	case 117:
		{
			yyVAL.vals = append(yyVAL.vals, yyS[yypt-0].val)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

func Parse(text string) *lex {

	l := &lex{
		tokens:     make(chan Token),
		State:      NewStats(),
		GlobalVars: map[string]interface{}{},
	}

	if Verbose {
		yyDebug = 3
	}

	go func() {
		s := NewScanner(strings.NewReader(strings.TrimSpace(text)))
		for {
			l.tokens <- s.Scan()
		}
	}()

	return l
}

func Run(l *lex) {
	yyParse(l)
}
