package parser

import "fmt"

type Stats struct {
	Assert Stat
	Must   Stat
	Should Stat
}

func NewStats() Stats {
	return Stats{
		Assert: NewStat(),
		Must:   NewStat(),
		Should: NewStat(),
	}
}

type Stat struct {
	Failed    int
	Succeeded int
	Messages  []string
}

func NewStat() Stat {
	return Stat{
		Failed:    0,
		Succeeded: 0,
		Messages:  make([]string, 0),
	}
}

//Prints current statistics generated by running assertion
func (s *Stats) PrintStats() {
	//print stats here.
	fmt.Printf("%+v\n", s)
}
