package parser

import "fmt"

type Stats struct {
	Assertion Stat
	Must      Stat
	Should    Stat
}

func NewStats() Stats {
	return Stats{
		Assertion: NewStat(),
		Must:      NewStat(),
		Should:    NewStat(),
	}
}

type Stat struct {
	Failed    int
	Succeeded int
}

func NewStat() Stat {
	return Stat{
		Failed:    0,
		Succeeded: 0,
	}
}

//Prints current statistics generated by running assertion
func (s *Stats) PrintStats() {
	//print stats here.
	fmt.Printf("%+v\n", s)
}
